services:

  postgres:
    image: postgres:15
    container_name: foodlink-postgres-fase-2
    environment:
      POSTGRES_DB: db_foodlink_v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_fase_2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./foodlink-api
    container_name: foodlink-api-fase-2
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  frontend:
    build:
      context: ./frontend
    container_name: foodlink-front-fase-2
    depends_on:
      - app
    ports:
      - "5173:5173"
    environment:
      VITE_API_PROXY_TARGET: http://app:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data_fase_2:
